# Generated by Django 6.1 on 2026-08-11 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_provider', models.CharField(choices=[('openstreetmap', 'OpenStreetMap'), ('google', 'Google Places')], default='openstreetmap', max_length=20)),
                ('google_api_key_encrypted', models.TextField(blank=True)),
                ('apollo_enabled', models.BooleanField(default=False)),
                ('apollo_api_key_encrypted', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
